
- name: distribute qcow2 file from 10.10.16.112 server to servers group
  synchronize:
    src: "{{ kvm_images_path }}/undercloud.qcow2"
    dest: "{{ kvm_images_path }}/undercloud.qcow2"
    rsync_opts:
      - "--sparse"
  delegate_to: 10.10.16.112